"""
Transform for M4 (Multi-generator, Multi-domain, and Multi-lingual Black-Box Machine-Generated Text Detection) Dataset.

This dataset contains text generated by various LLMs and human-written text across multiple domains.
Dataset URL: https://github.com/mbzuai-nlp/M4

Data format (jsonline):
    - prompt: str or list (the prompt/question text)
    - human_text: str or list (human-written text)
    - machine_text: str or list (model-generated text)
    - model: str (model used for generation, e.g., 'davinci', 'chatGPT', 'cohere', 'dolly-v2', 'bloomz', 'flan-t5', 'llama')
    - source: str (domain/source of the text, e.g., 'wikipedia', 'wikihow', 'reddit', 'arxiv', 'ruATD', 'baike', 'urdu-news', 'id-newspaper')
    - source_ID: str (unique identifier for the source)

Output: MultiClassSample instances with labels:
    - 0: human-written text
    - 1+: model-generated text (distinct labels for different models)
"""

import os
from pathlib import Path
from typing import Union

from ..registry import DatasetRegistry, DatasetTransform
from ..schemas import MultiClassSample
from ..readers import read_jsonl
from ..constants import DATASET_DIR_OTHERS, M4_DIRECTORY

# Map model names to integer labels. Starting from 1 to leave 0 for human text.
MODEL_TO_LABEL = {
    "human": 0,
    "davinci": 1,
    "chatGPT": 2,
    "cohere": 3,
    "dolly-v2": 4,
    "bloomz": 5,
    "flan-t5": 6,
    "llama": 7,
    # Add more models if needed
}

# Human-readable category names for output
MODEL_TO_CATEGORY = {
    "human": "Human Text",
    "davinci": "Davinci",
    "chatgpt": "ChatGPT",
    "cohere": "Cohere",
    "dolly-v2": "Dolly-v2",
    "bloomz": "Bloomz",
    "flan-t5": "Flan-T5",
    "llama": "Llama",
    # Add more models if needed
}


def _extract_texts(field: Union[str, list[str], None]) -> list[str]:
    """
    Convert a field that can be str, list[str], or None into a list of strings.
    """
    if field is None:
        return []
    if isinstance(field, str):
        return [field] if field.strip() else []
    if isinstance(field, list):
        return [item for item in field if isinstance(item, str) and item.strip()]
    return []

def _process_record(record: dict[str, any], text_type: str) -> list[MultiClassSample]:
    """
    Process a single record into a MultiClassSample.

    Args:
        record: The JSON record containing the data.
        text_type: Either "human" or "machine".

    Returns:
        MultiClassSample instance if valid, None otherwise.
    """
    samples = []

    if text_type == "human":
        texts = _extract_texts(record.get("human_text"))
        model = "human"
    else:
        texts = _extract_texts(record.get("machine_text"))
        model = record.get("model", "").lower()

    source = record.get("source", "")

    # For each text in the list, create a sample
    for text in texts:
        if len(text.strip()) < 10:
            continue

        label = MODEL_TO_LABEL.get(model)  # default for unknown models
        category = f"{MODEL_TO_CATEGORY.get(model)}-{source}"

        samples.append(MultiClassSample(
            text=text,
            label=label,
            category=category,
        ))

    return samples

def _process_file(file_path: Path) -> list[MultiClassSample]:
    """
    Process a single JSONL file and convert to MultiClassSample list.

    Args:
        file_path: Path to the JSONL file.

    Returns:
        List of MultiClassSample instances.
    """
    samples = []

    try:
        records = read_jsonl(str(file_path))
    except Exception as e:
        print(f"Warning: Failed to read {file_path}: {e}")
        return samples

    for record in records:
        # Process human texts (may return multiple samples)
        samples.extend(_process_record(record, "human"))
        # Process machine texts (may return multiple samples)
        samples.extend(_process_record(record, "machine"))

    return samples

@DatasetRegistry.register("M4")
class M4Transform(DatasetTransform):
    """
    Transform for M4 dataset (multi-class classification).

    Reads JSONL files with human and machine-generated text, producing MultiClassSample
    instances for each text sample.

    """

    output_schema = MultiClassSample

    def transform(self, raw_data: list[dict] = None, **kwargs) -> list[MultiClassSample]:
        """
        Transform M4 dataset into MultiClassSamples.

        Args:
            raw_data: List of dicts from JSONL. If not provided, reads from dataset_path.
            **kwargs: Additional arguments (path can be passed to override).

        Returns:
            List of MultiClassSample instances.
        """

        targetLLM = kwargs.get("targetLLM")
        if targetLLM is None:
            raise ValueError("TruthfulQA transform requires 'targetLLM' parameter")

        all_samples = []

        # If raw_data is not provided, read from files
        if not raw_data:
            # directory = M4_DIRECTORY
            directory = kwargs.get("path") or os.path.join(
                DATASET_DIR_OTHERS, "M4"
            )
            directory = Path(directory)
            # Find all JSONL files
            jsonl_files = list(directory.glob("*.jsonl"))

            for file_path in jsonl_files:
                samples = _process_file(file_path)
                all_samples.extend(samples)

        else:
            for record in raw_data:
                all_samples.extend(_process_record(record, "human"))
                all_samples.extend(_process_record(record, "machine"))

        print(f"Total samples loaded: {len(all_samples)}")
        return all_samples